"""Initial migration

Revision ID: 4ab8a191763e
Revises: 
Create Date: 2025-03-13 20:39:35.972017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab8a191763e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_PSI', sa.Integer(), nullable=False),
    sa.Column('SCM_pct', sa.Float(), nullable=False),
    sa.Column('CM_mass', sa.Float(), nullable=False),
    sa.Column('mixture_co2e_total', sa.Float(), nullable=False),
    sa.Column('test_PSI', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
